# Generated by Django 5.0.6 on 2024-06-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
