# Generated by Django 5.0.6 on 2024-07-06 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwanttosay_app', '0002_alter_texts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='password',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
